"""The site assembler, and the guards that keep the navigation honest.

Three kinds of test live here.

The FIRST kind exercises :mod:`macro_core.site` as a module, on synthetic
markup: that a Socratic section is lifted apart correctly, that anchoring and
wrapping are idempotent, that a manuscript skeleton is told apart from a
draft, that relative links come out right at both page depths.

The SECOND kind is the REGRESSION GUARD this file mainly exists for.  The
complaint that produced this module was not "a page is missing"; measured
before the rebuild, exactly one page was unreachable.  It was that a reader
had no sense of place.  So the guards assert PLACE, on the real ``docs/``
tree: every page carries the project row, a breadcrumb and a question rail;
every page is reachable from the front door; no page is a leaf you cannot
climb out of.  A future renderer that emits a page and forgets to let the
assembler see it fails here rather than becoming the next orphan.

The THIRD kind guards the theme.  The site's status colours mean something,
and they mean it in one place — ``docs/assets/macro.css``.  A renderer that
inlines a colour literal is a second stylesheet with no name, and that is
exactly how 85 figures and a dozen table cells ended up styled for a dark
ground that no longer exists.  :func:`test_no_renderer_inlines_a_colour`
closes it.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

import pytest

from macro_core import project_plan as pp
from macro_core import provenance as pv
from macro_core import site

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DOCS_DIR = REPO_ROOT / "docs"
PIPELINE_DIR = REPO_ROOT / "pipeline"

#: A page in the house shape, as the thirteen report renderers emit it.
SAMPLE = """<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<title>S9 — A Worked Example</title>
<link rel="stylesheet" href="../assets/macro.css">
</head><body>

<header>
  <h1>S9 &mdash; A Worked Example</h1>
  <p>Built 2026-08-21 &middot; <a href="../index.html">back</a></p>
</header>

<nav><a href="#one">1 First</a> &middot; <a href="#two">2 Second</a></nav>

<section id="one">
<div class="bhead"><h2>1 &middot; Does the shutter lie?</h2>
<span class="tag">3.4 s, measured on 812 frames</span></div>
<div class="stage"><h3>Question</h3>
<p class="sub">The header claims one exposure length and the photometry
implies another. Which one is the shutter actually doing?</p>
<h3>Evidence</h3>
<figure><img src="figures/s9/shutter.png" alt="">
<figcaption>Measured minus commanded exposure, per night.</figcaption>
</figure>
<h3>Decision</h3>
<div class="decision">The <b>header is right</b>; the discrepancy is
scattered light, not timing.</div>
</div>
</section>

<section id="two">
<div class="bhead"><h2>2 &middot; Second question</h2></div>
<div class="stage"><h3>Question</h3>
<p>Short one.</p>
</div>
</section>

<footer>Generated by <code>macro_core.report_s9</code>.</footer>
</body></html>
"""

#: The other shape found in the wild: sections with no ids at all, so there
#: was nowhere for a link to land.
UNANCHORED = """<html><head><title>T</title></head><body>
<div class='wrap'><h1>Loose page</h1>
<h2>1 &middot; Alpha</h2><p>Body of alpha.</p>
<h2>2 &middot; Beta</h2><p>Body of beta.</p>
</div></body></html>
"""


def _write(tmp_path: Path, rel: str, text: str) -> Path:
    path = tmp_path / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


# ===========================================================================
# 1.  THE TOP ROW
# ===========================================================================

def test_every_project_in_the_ledger_has_a_row_label():
    """The one hand-stated table in this module, guarded.

    ``SHORT_LABEL`` exists because a project's title is a sentence and a
    navigation row needs two words.  It is the only thing here that is not
    derived, so the only acceptable failure mode is loud: adding a seventh
    project must break this test, not quietly print a blank tab.
    """
    site.validate()
    for project in pp.PROJECTS:
        label = site.SHORT_LABEL[project.key]
        assert label and len(label) <= 18, project.key


def test_a_project_with_no_row_label_is_refused(monkeypatch):
    monkeypatch.setitem(site.SHORT_LABEL, "CV_TimeSeries", "CV")
    monkeypatch.delitem(site.SHORT_LABEL, "CV_TimeSeries")
    with pytest.raises(site.SiteError, match="SHORT_LABEL"):
        site.validate()


def test_a_row_label_with_no_project_is_refused(monkeypatch):
    monkeypatch.setitem(site.SHORT_LABEL, "Imaginary_Project", "Ghost")
    with pytest.raises(site.SiteError, match="does not declare"):
        site.validate()


def test_the_row_is_the_pipeline_then_the_ledgers_own_project_order():
    """No re-sorting.  A navigation row with its own opinion about ordering
    is a second source of truth about what the plan says comes first."""
    keys = [a.key for a in site.areas()]
    assert keys[0] == site.PIPELINE
    assert keys[1:] == [p.key for p in pp.PROJECTS]
    assert site.areas()[0].is_pipeline
    assert not any(a.is_pipeline for a in site.areas()[1:])


# ===========================================================================
# 2.  THE HARVEST
# ===========================================================================

def test_a_socratic_section_is_lifted_into_its_four_parts(tmp_path):
    path = _write(tmp_path, "pipeline/s9.html", SAMPLE)
    doc = site.harvest_page(path, "pipeline/s9.html")
    assert doc.title == "S9 — A Worked Example"
    assert len(doc.questions) == 2

    first = doc.questions[0]
    assert first.anchor == "one"
    assert "shutter actually doing" in first.ask
    assert first.deciding == "3.4 s, measured on 812 frames"
    assert "header is right" in first.decision
    assert first.fig_src == "pipeline/figures/s9/shutter.png"
    assert "Measured minus commanded" in first.fig_caption


def test_the_rail_label_prefers_the_question_over_the_heading():
    """"Pointing validation" tells a reader less than the question the
    section actually asks, and the pages carry both."""
    q = site.Question(page="p", anchor="a", number=1,
                      heading="5 &middot; Pointing validation",
                      ask="Do the coordinates in the header point where the "
                          "telescope was looking?",
                      deciding="", decision="", fig_src="", fig_caption="")
    assert q.label.startswith("Do the coordinates")
    bare = site.Question(page="p", anchor="a", number=1,
                         heading="5 &middot; Pointing validation", ask="",
                         deciding="", decision="", fig_src="",
                         fig_caption="")
    # The section's own number is dropped: this view supplies one, and
    # "5  5 · Pointing validation" is how generated navigation starts to
    # look machine-made.
    assert bare.label == "Pointing validation"


def test_rail_labels_stay_short_enough_to_scan():
    """Fifteen seconds for the whole rail is the requirement, so no entry
    may run past two lines of a 258 px column."""
    build = site.Build(DOCS_DIR, REPO_ROOT, site.DEFAULT_MANIFEST)
    for doc in build.pages.values():
        for question in doc.questions:
            assert len(question.label) <= site.RAIL_CHARS + 1, question.page


def test_a_page_with_no_section_ids_gets_anchors_it_can_be_linked_to(tmp_path):
    """Two real pages emitted sections with no id, so their headings could
    not be linked to — the 'no clear breadcrumbs' complaint from the other
    end: there was nowhere to land."""
    path = _write(tmp_path, "pipeline/loose.html", UNANCHORED)
    doc = site.harvest_page(path, "pipeline/loose.html")
    assert [q.anchor for q in doc.questions] == ["sec-1", "sec-2"]
    assert [q.title for q in doc.questions] == ["1 · Alpha", "2 · Beta"]


def test_anchoring_is_idempotent():
    once = site.assign_anchors(site.page_body(UNANCHORED))
    twice = site.assign_anchors(once)
    assert once == twice
    assert once.count('class="qanchor"') == 2


def test_anchoring_never_renames_an_id_a_renderer_supplied():
    body = site.page_body(SAMPLE)
    assert site.assign_anchors(body) == body


def test_a_figure_outside_every_section_still_belongs_to_the_page(tmp_path):
    html = SAMPLE.replace(
        "<footer>", '<figure><img src="figures/s9/loose.png">'
                    "<figcaption>Orphan.</figcaption></figure>\n<footer>")
    path = _write(tmp_path, "pipeline/s9.html", html)
    doc = site.harvest_page(path, "pipeline/s9.html")
    assert "pipeline/figures/s9/loose.png" in {f.src for f in doc.figures}


def test_figure_paths_resolve_relative_to_the_page_that_shows_them():
    assert site._normalise(site._resolve("CV_TimeSeries/a.html",
                                         "figures/cv/x.png")) == \
        "CV_TimeSeries/figures/cv/x.png"
    assert site._normalise(site._resolve("pipeline/a.html",
                                         "../CV_TimeSeries/f/x.png")) == \
        "CV_TimeSeries/f/x.png"


# ===========================================================================
# 3.  WRAPPING — the operation that must never eat a page
# ===========================================================================

def _build_for(tmp_path: Path) -> site.Build:
    """A Build over a throwaway docs tree, with no manifest behind it."""
    return site.Build(tmp_path, REPO_ROOT, manifest=None)


def test_wrapping_is_idempotent_and_never_nests_chrome(tmp_path):
    """A renderer may re-run at any time, so the assembler has to be able to
    run again on its own output.  Without recovering the original body
    first, the second build would nest chrome inside chrome and the third
    would nest it again."""
    _write(tmp_path, "pipeline/s9.html", SAMPLE)
    build = _build_for(tmp_path)
    area = build.area_by_key[site.PIPELINE]
    site.wrap_page(build, area, "pipeline/s9.html", ["pipeline/s9.html"])
    once = (tmp_path / "pipeline/s9.html").read_text()
    site.wrap_page(build, area, "pipeline/s9.html", ["pipeline/s9.html"])
    twice = (tmp_path / "pipeline/s9.html").read_text()
    assert once == twice
    assert once.count(site.CONTENT_BEGIN) == 1
    assert once.count(site.CONTENT_END) == 1
    assert once.count('class="topbar"') == 1


def test_wrapping_keeps_the_renderers_markup_byte_for_byte(tmp_path):
    _write(tmp_path, "pipeline/s9.html", SAMPLE)
    build = _build_for(tmp_path)
    site.wrap_page(build, build.area_by_key[site.PIPELINE],
                   "pipeline/s9.html", ["pipeline/s9.html"])
    wrapped = (tmp_path / "pipeline/s9.html").read_text()
    recovered = site.original_content(site.page_body(wrapped))
    assert recovered == site.page_body(SAMPLE)


def test_wrapping_adds_the_stylesheet_to_a_page_that_lacked_one(tmp_path):
    """``pipeline_status.html`` links no shared stylesheet — it was written
    to stand alone, because nothing linked to it."""
    _write(tmp_path, "pipeline/loose.html", UNANCHORED)
    build = _build_for(tmp_path)
    site.wrap_page(build, build.area_by_key[site.PIPELINE],
                   "pipeline/loose.html", ["pipeline/loose.html"])
    head = (tmp_path / "pipeline/loose.html").read_text().split("<body")[0]
    assert "../assets/macro.css" in head


def test_prev_and_next_walk_the_evidence_chain(tmp_path):
    for name in ("a", "b", "c"):
        _write(tmp_path, f"pipeline/{name}.html",
               SAMPLE.replace("A Worked Example", f"Page {name.upper()}"))
    build = _build_for(tmp_path)
    siblings = ["pipeline/a.html", "pipeline/b.html", "pipeline/c.html"]
    area = build.area_by_key[site.PIPELINE]
    site.wrap_page(build, area, "pipeline/b.html", siblings)
    middle = (tmp_path / "pipeline/b.html").read_text()
    assert "a.html" in middle and "c.html" in middle
    assert "Previous" in middle and "Next" in middle
    site.wrap_page(build, area, "pipeline/a.html", siblings)
    first = (tmp_path / "pipeline/a.html").read_text()
    assert "Previous" not in first


# ===========================================================================
# 4.  CHROME AND FINGERPRINTS MUST NOT FIGHT
# ===========================================================================

def test_the_content_markers_are_the_same_string_in_both_modules():
    """``provenance`` cannot import ``site`` (``site`` imports it), so the
    markers are declared twice.  They may never drift apart: if they did,
    every published page would look modified to the DAG forever."""
    assert pv.SITE_CONTENT_BEGIN.decode() == site.CONTENT_BEGIN
    assert pv.SITE_CONTENT_END.decode() == site.CONTENT_END


def test_wrapping_a_page_does_not_change_its_provenance_fingerprint(tmp_path):
    """THE POINT OF ``published_content``.

    A stage's output is what the stage wrote.  If re-arranging the furniture
    around a report invalidated the report, every site build would post a
    sweep of STALE verdicts across sixteen stages whose numbers had not
    moved — and a status page that cries stale about everything teaches its
    reader to stop looking.
    """
    _write(tmp_path, "pipeline/s9.html", SAMPLE)
    before = pv.digest_bytes(pv.published_content(SAMPLE.encode()))
    build = _build_for(tmp_path)
    site.wrap_page(build, build.area_by_key[site.PIPELINE],
                   "pipeline/s9.html", ["pipeline/s9.html"])
    after_bytes = (tmp_path / "pipeline/s9.html").read_bytes()
    after = pv.digest_bytes(pv.published_content(after_bytes))
    assert before == after
    # And the raw bytes really did change, so the test is testing something.
    assert pv.digest_bytes(after_bytes) != pv.digest_bytes(SAMPLE.encode())


def test_the_first_wrap_of_a_page_is_free(tmp_path):
    """An unwrapped page hashes to its BODY, not its bytes.

    Without that fallback, the build that first put chrome on a page would
    move its fingerprint once — a one-off sweep of false staleness across
    every published report, which is the same lie as a permanent one, told
    once.  So the artifact is the body either way.
    """
    raw = b"<html><head><title>x</title></head><body>the report</body></html>"
    assert pv.published_content(raw) == b"the report"
    wrapped = (b"<html><head><title>x</title></head><body><nav>chrome</nav>"
               + pv.SITE_CONTENT_BEGIN + b"the report" + pv.SITE_CONTENT_END
               + b"</body></html>")
    assert pv.published_content(wrapped) == b"the report"


def test_something_that_is_not_a_document_is_still_hashed_whole():
    raw = b"target,frames\nSTLMi,812\n"
    assert pv.published_content(raw) == raw


# ===========================================================================
# 5.  THE VIEWS — what exists, and what says it does not
# ===========================================================================

def test_a_view_that_does_not_exist_is_named_rather_than_linked():
    """"Draft Paper — none yet" beats a link to a title page.  Linking a
    stub is the specific failure the brief called out."""
    build = site.Build(DOCS_DIR, REPO_ROOT, site.DEFAULT_MANIFEST)
    tabs = {t.label: t for t in
            build.tabs_for(build.area_by_key["TCrB_Monitoring"])}
    assert tabs["Draft Paper"].rel == ""
    assert tabs["Draft Paper"].why_absent
    assert tabs["The Case"].rel and tabs["Plan & Status"].rel
    cv = {t.label: t for t in
          build.tabs_for(build.area_by_key["CV_TimeSeries"])}
    assert cv["Draft Paper"].rel == "CV_TimeSeries/paper.html"


def test_exactly_one_project_has_a_draft_and_it_is_measured_not_declared():
    """Five projects carry the same AASTeX skeleton and two of them have a
    compiled PDF, so neither a ``main.tex`` nor a ``main.pdf`` distinguishes
    a draft.  Prose does."""
    build = site.Build(DOCS_DIR, REPO_ROOT, site.DEFAULT_MANIFEST)
    with_draft = [a.key for a in build.areas if build.paper_pdf(a)]
    assert with_draft == ["CV_TimeSeries"]


def test_a_skeleton_and_a_draft_are_far_apart_not_near_the_threshold():
    """The threshold is only allowed to be a constant because the gap it
    sits in is enormous.  If that stops being true this test says so before
    a reader is told an outline is a paper."""
    def longest(key: str) -> int:
        tex = (REPO_ROOT / "manuscripts" / key / "main.tex")
        return max([s.chars for s in site.tex_sections(
            tex.read_text(encoding="utf-8"))] or [0])

    assert longest("CV_TimeSeries") > 10 * site.WRITTEN_CHARS
    for key in ("TCrB_Monitoring", "BeStar_Grism", "SN2023ixf_LightCurve",
                "DwarfGalaxy_AGN_Survey"):
        assert longest(key) < site.WRITTEN_CHARS / 4, key


def test_the_end_matter_is_not_credited_to_the_last_section():
    """The T CrB skeleton's Conclusions measured 372 characters — the
    acknowledgments and the bibliography call, which sit after the last
    ``\\section`` — while its five siblings measured under 25."""
    sections = site.tex_sections(
        (REPO_ROOT / "manuscripts" / "TCrB_Monitoring"
         / "main.tex").read_text(encoding="utf-8"))
    assert sections and max(s.chars for s in sections) < 50


def test_an_appendix_survives_the_end_matter_cut():
    """AASTeX puts the acknowledgments BEFORE ``\\appendix`` and the
    bibliography after it, so one cut at the first marker would delete the
    appendix along with the apparatus."""
    sections = site.tex_sections(
        (REPO_ROOT / "manuscripts" / "CV_TimeSeries"
         / "main.tex").read_text(encoding="utf-8"))
    assert any(s.is_appendix for s in sections)


def test_the_pipeline_fraction_counts_one_stage_per_page():
    """Every pipeline stage has a paired ``R-*`` review stage pointing at the
    same report, so counting through ``stage_report_path`` made the row
    announce a denominator nearly twice the number of pages behind it."""
    stages = site.pipeline_stages(DOCS_DIR)
    pages = [rel for _, rel in stages]
    assert len(pages) == len(set(pages))
    assert len(stages) >= 9
    for key, rel in stages:
        assert pp.stage_report_path(key) == f"docs/{rel}"


def test_a_page_is_judged_by_its_analysis_not_by_its_renderer():
    """S2's detector tables were wiped, so ``S2`` reads DESTROYED while the
    renderer that drew the page, ``R-S2``, reads merely STALE.  Showing the
    renderer's verdict beside S2's High Gain ceiling would tell a reader the
    number was out of date when the truth is that nothing backs it."""
    rel = "pipeline/s2_detector.html"
    assert site.analysis_stage_of(rel) == "S2"
    assert pv.producer_of(f"file:docs/{rel}") == "R-S2"
    for _, page in site.pipeline_stages(DOCS_DIR):
        assert not site.analysis_stage_of(page).startswith("R-"), page


def test_every_page_that_reprints_a_measurement_carries_its_verdict():
    """The Case view and the Figures wall quote numbers measured elsewhere.
    A quoted number without its verdict is the site re-asserting a
    measurement whose table may no longer exist."""
    build = site.Build(DOCS_DIR, REPO_ROOT, site.DEFAULT_MANIFEST)
    for area in build.areas:
        if not build.questions_of(area):
            continue
        case = (DOCS_DIR / area.home).read_text()
        assert 'class="chip v-' in case, area.key


def test_inherited_pages_come_from_the_tasks_own_stage_edges():
    """The edge that makes staleness propagate into the plan is the same
    edge that says which pipeline evidence a project depends on.  There is
    no second list."""
    project = pp.PROJECT_BY_KEY["TCrB_Monitoring"]
    inherited = site.inherited_pages(project)
    assert inherited
    expected = {pp.stage_report_path(t.stage) for t in project.tasks}
    for rel in inherited:
        assert f"docs/{rel}" in expected
        assert rel.startswith("pipeline/")


# ===========================================================================
# 6.  THE GUARDS — on the real docs/ tree
# ===========================================================================

@pytest.fixture(scope="module")
def pages() -> dict[str, str]:
    return {p.relative_to(DOCS_DIR).as_posix(): p.read_text(encoding="utf-8")
            for p in sorted(DOCS_DIR.rglob("*.html"))}


def test_every_published_page_carries_the_project_row(pages):
    """LAYER 1, on every page without exception.  This is the test that
    would have caught the old ``pipeline_status.html``, which wore no site
    furniture at all because nothing linked to it."""
    for rel, html in pages.items():
        assert 'class="topbar"' in html, rel
        for area in site.areas():
            assert f">{site.esc(area.label)}<" in html, f"{rel}: {area.label}"


def test_every_published_page_carries_a_breadcrumb_home(pages):
    for rel, html in pages.items():
        assert 'class="crumbs"' in html, rel
        if rel != site.LANDING:
            assert re.search(r'<a href="[^"]*index\.html">Home</a>', html), rel


def test_every_published_page_carries_a_question_rail(pages):
    """LAYER 3.  A page with sections but no rail is a page a reader has to
    scroll blind."""
    for rel, html in pages.items():
        if 'class="rail"' in html:
            continue
        # The only pages allowed no rail are those with nothing to list.
        assert "<h2" not in html, f"{rel} has sections but no question rail"


def test_no_page_is_orphaned_from_the_front_door(pages):
    """Reachability, computed rather than asserted.

    The measured starting point was ONE unreachable page.  The rebuild's
    promise is that there is now no way to produce a second one without a
    test noticing, because the chrome that makes a page reachable is applied
    to every page by the same pass.
    """
    reachable, frontier = {site.LANDING}, [site.LANDING]
    while frontier:
        current = frontier.pop()
        for href in re.findall(r'href="([^"#?]+)', pages.get(current, "")):
            if not href.endswith(".html") or href.startswith("http"):
                continue
            target = site._normalise(
                (Path(current).parent / href).as_posix())
            if target in pages and target not in reachable:
                reachable.add(target)
                frontier.append(target)
    assert set(pages) - reachable == set()


def test_the_case_of_every_area_is_one_click_from_the_front_door(pages):
    landing = pages[site.LANDING]
    for area in site.areas():
        assert f'href="{area.home}"' in landing, area.key


def test_every_generated_figure_appears_on_a_figures_wall():
    """The Figures view is often the first thing a collaborator opens.  A
    plot that exists on disk and appears on no wall is a plot nobody will
    ever find — which is what had happened to the thirteen manuscript
    figures, built straight into the paper and shown on no page at all."""
    build = site.Build(DOCS_DIR, REPO_ROOT, site.DEFAULT_MANIFEST)
    shown = {f.src for area in build.areas for f in build.figures_of(area)}
    on_disk = {p.relative_to(DOCS_DIR).as_posix()
               for p in DOCS_DIR.rglob("figures/**/*.png")}
    assert on_disk - shown == set()


def test_the_manuscript_figures_carry_the_manuscripts_own_captions():
    """They belong to no page, so their captions come from ``p5_figure`` —
    the same table the LaTeX pastes from, which is why the Figures view and
    the paper cannot disagree about what a figure says."""
    build = site.Build(DOCS_DIR, REPO_ROOT, site.DEFAULT_MANIFEST)
    assert len(build.paper_figs) == 13
    for figure in build.paper_figs:
        assert figure.category == "cv_paper"
        assert len(figure.caption) > 60


def test_every_evidence_page_reachable_before_the_rebuild_is_still_there():
    """The detail layer is a promotion, not a deletion.  Every page the site
    published before this module existed must still exist and still be
    served."""
    for rel in ("pipeline/s0_manifest.html", "pipeline/s0b_calibration_"
                "inventory.html", "pipeline/s0c_staging.html",
                "pipeline/s0e_geometry_fix.html", "pipeline/s1_astrometry.html",
                "pipeline/s2_detector.html", "pipeline/s2c_filter_identity.html",
                "pipeline/s3_timing.html", "pipeline/s4_photometry.html",
                "pipeline/pipeline_status.html",
                "CV_TimeSeries/cv_catalogue_tie.html",
                "CV_TimeSeries/cv_characterization.html",
                "CV_TimeSeries/cv_external_context.html",
                "CV_TimeSeries/cv_final_science.html",
                "CV_TimeSeries/cv_phase2_completion.html",
                "CV_TimeSeries/cv_timeseries_analysis.html",
                "SN2023ixf_LightCurve/sn_gate0.html",
                "index.html", "evidence.html"):
        assert (DOCS_DIR / rel).exists(), rel


# ===========================================================================
# 7.  THE THEME
# ===========================================================================

STYLESHEET = DOCS_DIR / "assets" / "macro.css"

#: Every renderer that writes HTML.  Kept as a glob rather than a list so a
#: fourteenth renderer is covered the day it is written.
RENDERERS = sorted(
    p for p in PIPELINE_DIR.rglob("report_*.py")
    if "tests" not in p.parts)

_INLINE_COLOUR_RE = re.compile(
    r"""["']?\s*(?:color|background(?:-color)?)\s*:\s*[#a-zA-Z0-9]""")


def test_the_renderers_exist_and_this_guard_is_looking_at_them():
    assert len(RENDERERS) >= 13


def test_no_renderer_inlines_a_colour(monkeypatch):
    """One stylesheet, or none.

    A ``style="color:#9fd8ae"`` is a second stylesheet with no name and no
    reviewer.  Twelve of them survived the move to a light theme by turning
    pale-green text onto white — legible only to somebody who already knew
    what it said.  Renderers now ask for ``.ok`` / ``.warn`` / ``.bad`` /
    ``.muted``, which are defined once, in one file, against one ground.

    ``report_provenance`` is exempt: it emits a complete standalone document
    with its own token block, declared as such, and it is the only page that
    has to render outside this site (it is written by the status CLI).
    """
    offenders = []
    for path in RENDERERS:
        if path.name == "report_provenance.py":
            continue
        for n, line in enumerate(path.read_text().splitlines(), start=1):
            if "style=" in line and _INLINE_COLOUR_RE.search(line):
                offenders.append(f"{path.name}:{n}: {line.strip()[:90]}")
    assert not offenders, "inline colour(s):\n" + "\n".join(offenders)


def test_no_published_page_inlines_a_colour():
    """The same guard from the other end, on the output.  A renderer could
    be clean and a page still dirty if the page was never regenerated."""
    offenders = [rel.name for rel in DOCS_DIR.rglob("*.html")
                 if re.search(r'style="[^"]*color:', rel.read_text())
                 and rel.name != "pipeline_status.html"]
    assert not offenders


def test_the_stylesheet_defines_every_status_class_the_site_emits():
    """Status colour is meaning here, so a chip whose class the stylesheet
    has never heard of renders as unstyled text — the one failure mode that
    looks like a design choice rather than a bug."""
    css = STYLESHEET.read_text()
    for status in pp.ALL_STATUSES:
        assert f".chip.{status}" in css or f",.chip.{status}" in css, status
    for verdict in ("v-fresh", "v-stale", "v-wait", "v-never", "v-gone"):
        assert verdict in css, verdict
    for ink in (".ok", ".bad", ".warn", ".muted"):
        assert ink in css, ink


def test_the_stylesheet_is_light():
    """James chose light over the old dark theme: "light and airy is more
    professional".  The body ground is the one declaration that decides it,
    and it is easy to lose in a merge."""
    css = STYLESHEET.read_text()
    assert "--bg:        #ffffff" in css or "--bg:#ffffff" in css
    # And nothing may re-declare a near-black page ground.
    assert not re.search(r"body\s*\{[^}]*background:\s*#0", css)


def test_no_page_flips_to_a_dark_palette_on_a_dark_desktop():
    """One page used to, and it was the one page nothing linked to, so
    nobody ever saw the seam.  Wrapped in light chrome, a reader with a dark
    OS got a light top bar around a black page."""
    for path in DOCS_DIR.rglob("*.html"):
        text = path.read_text()
        if "prefers-color-scheme" not in text:
            continue
        dark = re.search(r"prefers-color-scheme\s*:\s*dark\s*\)\s*\{"
                         r"[^}]*--bg\s*:\s*#0", text)
        assert not dark, path.name


# ===========================================================================
# 8.  THE WHOLE BUILD
# ===========================================================================

def test_a_full_build_is_byte_stable(tmp_path):
    """Run it twice, get the same site.

    This is what makes ``build_site.py --check`` mean something and a git
    diff worth reading.  It is also why the chrome footer carries no build
    timestamp: a stamp would make every page differ on every build, and the
    signal would be gone.
    """
    docs = tmp_path / "docs"
    shutil.copytree(DOCS_DIR, docs,
                    ignore=shutil.ignore_patterns("*.png", "*.svg"))
    site.build_site(manifest=None, docs_dir=docs, repo_root=REPO_ROOT)
    first = {p: p.read_bytes() for p in docs.rglob("*.html")}
    site.build_site(manifest=None, docs_dir=docs, repo_root=REPO_ROOT)
    second = {p: p.read_bytes() for p in docs.rglob("*.html")}
    assert first == second


def test_a_build_writes_a_case_and_an_evidence_index_for_every_area(tmp_path):
    docs = tmp_path / "docs"
    shutil.copytree(DOCS_DIR, docs,
                    ignore=shutil.ignore_patterns("*.png", "*.svg"))
    written = site.build_site(manifest=None, docs_dir=docs,
                              repo_root=REPO_ROOT)
    names = {p.relative_to(docs).as_posix() for p in written}
    assert site.LANDING in names
    for area in site.areas():
        assert area.home in names, area.key
        assert f"{area.dir}/evidence.html" in names, area.key


def test_a_view_whose_condition_lapses_is_removed_not_left_behind(tmp_path):
    """A door onto a room that no longer exists is the orphan class this
    rebuild set out to close — and the first build here produced one."""
    docs = tmp_path / "docs"
    shutil.copytree(DOCS_DIR, docs,
                    ignore=shutil.ignore_patterns("*.png", "*.svg"))
    stale = docs / "Legacy_Rigel" / "paper.html"
    stale.parent.mkdir(parents=True, exist_ok=True)
    stale.write_text("<html><body>a draft that never was</body></html>")
    site.build_site(manifest=None, docs_dir=docs, repo_root=REPO_ROOT)
    assert not stale.exists()


def test_the_build_never_deletes_a_page_a_renderer_wrote(tmp_path):
    docs = tmp_path / "docs"
    shutil.copytree(DOCS_DIR, docs,
                    ignore=shutil.ignore_patterns("*.png", "*.svg"))
    keep = docs / "pipeline" / "s3_timing.html"
    site.build_site(manifest=None, docs_dir=docs, repo_root=REPO_ROOT)
    assert keep.exists()


def test_relative_links_are_right_at_both_page_depths():
    assert site.rel_href("index.html", "assets/macro.css") == "assets/macro.css"
    assert site.rel_href("pipeline/s3.html", "assets/macro.css") == \
        "../assets/macro.css"
    assert site.rel_href("CV_TimeSeries/case.html", "index.html") == \
        "../index.html"


def test_an_area_prefix_is_stripped_from_a_page_title_inside_that_area():
    """Six rows all reading "Cataclysmic-Variable Time Series — …" is a
    column of near-identical strings; the distinguishing half is the tail."""
    assert site.within("Cataclysmic-Variable Time Series",
                       "Cataclysmic-Variable Time Series — the catalogue "
                       "tie") == "The catalogue tie"
    assert site.within("Other Project", "S3 — The Shared Time Axis") == \
        "S3 — The Shared Time Axis"
