# DRAFT -- NOT LOADED, NOT VALIDATED BY pyscope.telrun.
# T CrB eruption response: peak, V 2-4
# Generated by pipeline/scripts/ops_exposure.py v1.0 (2026-10-03); do not edit by hand.
# Exposures are a x4 ladder so that at least one rung is
# well exposed whatever the star is doing; see README.md.
# Site: fill in observer and code; check keyword spelling
# against your pyscope version; then dry-run and send the log.

title "T CrB eruption - peak, V 2-4"
observer "<observer e-mail>"
code "<observing code>"

block start
    priority 1
    do_not_interrupt true
    source "T CrB"
    ra 15:59:30.16
    dec +25:55:12.6
    binning 2x2
    repositioning true
    filter lrg exposure 0.22 nexp 1
    filter lrg exposure 0.89 nexp 1
    filter lrg exposure 3.6 nexp 1
    filter lrg exposure 14 nexp 1
    filter lrg exposure 23 nexp 1
    filter hrg exposure 0.43 nexp 1
    filter hrg exposure 1.7 nexp 1
    filter hrg exposure 7 nexp 1
    filter hrg exposure 28 nexp 1
    filter hrg exposure 44 nexp 1
block end
