# DRAFT -- NOT LOADED, NOT VALIDATED BY pyscope.telrun.
# T CrB eruption response: late decline and secondary maximum, V 7-10
# Generated by pipeline/scripts/ops_exposure.py v1.0 (2026-10-03); do not edit by hand.
# Exposures are a x4 ladder so that at least one rung is
# well exposed whatever the star is doing; see README.md.
# Site: fill in observer and code; check keyword spelling
# against your pyscope version; then dry-run and send the log.

title "T CrB eruption - late decline and secondary maximum, V 7-10"
observer "<observer e-mail>"
code "<observing code>"

block start
    priority 1
    do_not_interrupt true
    source "T CrB"
    ra 15:59:30.16
    dec +25:55:12.6
    binning 2x2
    repositioning true
    filter lrg exposure 22 nexp 1
    filter lrg exposure 89 nexp 1
    filter lrg exposure 240 nexp 1
    filter hrg exposure 43 nexp 1
    filter hrg exposure 170 nexp 1
    filter hrg exposure 240 nexp 1
    filter g exposure 0.36 nexp 1
    filter g exposure 1.5 nexp 1
    filter g exposure 5.8 nexp 1
    filter g exposure 23 nexp 1
    filter g exposure 93 nexp 1
    filter r exposure 0.25 nexp 1
    filter r exposure 1 nexp 1
    filter r exposure 4 nexp 1
    filter r exposure 16 nexp 1
    filter r exposure 63 nexp 1
    filter i exposure 0.23 nexp 1
    filter i exposure 0.9 nexp 1
    filter i exposure 3.6 nexp 1
    filter i exposure 14 nexp 1
    filter i exposure 57 nexp 1
block end
